name: Solution Check
on:
  workflow_dispatch:
    inputs:
      sample_name:
        description: Which sample do you want to run a solution check on?
jobs:
  pack-solution:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
            solution-folder: samples/${{ github.event.inputs.sample_name }}/sourcecode
            solution-file: samples/${{ github.event.inputs.sample_name }}/solution/${{ github.event.inputs.sample_name }}.zip
            solution-type: Unmanaged
      - name: Check Solution
        uses: microsoft/powerplatform-actions/check-solution@v0
        with: samples/${{ github.event.inputs.sample_name }}/solution/${{ github.event.inputs.sample_name }}.zip